package com.SteamGame.login.dto;

public enum ResultCode {
    REGISTER_OK,
    LOGIN_OK,
    CONFIG_NOT_FOUND,
    CONFIG_INVALID,
    DECRYPT_FAILED,
    INVALID_STEAM_ID,
    INVALID_API_KEY_FORMAT,
    INVALID_KEY_OR_USER,
    STEAM_API_TIMEOUT,
    STEAM_API_UNAVAILABLE,
    PROFILE_PRIVATE_OR_NO_GAMES,
    INTERNAL_ERROR
}
