spring:
  application:
    name: steam-launcher
  datasource:
    url: jdbc:h2:file:./data/steamdb;DATABASE_TO_UPPER=false;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  sql:
    init:
      mode: always
server:
  port: 8080

login:
  config:
    path: auth.yaml
  cache:
    revalidateHours: 6
    failRetryHours: 1
    maxPerRun: 50
    schedulerEnabled: true
