spring:
  application:
    name: steam-launcher
server:
  port: 8080

login:
  config:
    path: auth.yaml
  encryption:
    base64Key: ${STEAMGAME_CREDENTIAL_KEY:}
  cache:
    revalidateHours: 6
    failRetryHours: 1
    maxPerRun: 50
    schedulerEnabled: true